Repository SamarthTech/noncode-projects-2024, pull requests merged in 2024-10, with the labels that each got.

#2 Added a important open source documentation
  Open Source Documentation/Readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#1 Added Documentation for React JS
  React JS Docomentation/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#4 Added Redux Toolkit concept in the ReactJS Documentation
  React JS Docomentation/README.md
Labels: dino-accepted

#7 Database Documentation
  Database Documentation/README.md
Labels: open-odyssey, dino-accepted

#8 Added documentation for Decentralized Application (DAPP)
  Decentralized Application (DAPP) Documentation/1_X6Kb4P4kuNn9Doiqwy2peQ.png
  Decentralized Application (DAPP) Documentation/360_F_193545415_6pzIxsRxtPenzgxfVqtuXCG2BE8vitif.jpg
  Decentralized Application (DAPP) Documentation/360_F_196968684_zp8obttcJzlY4tWhFHzDGOTbPkdY0Q3p.jpg
  Decentralized Application (DAPP) Documentation/66bcd4e36a56a4f20095a5e9_643ebbd4a4ebb5e3235dbae0_Chainlink-Whitepaper-Blog-Diagram-1.webp
  Decentralized Application (DAPP) Documentation/ETH-USD-Price-Feeds.webp
  Decentralized Application (DAPP) Documentation/Educational-Series_Blockchain-Graphic-V4-1536x1195.webp
  Decentralized Application (DAPP) Documentation/Howdoesasmartcontractwork1.png
  Decentralized Application (DAPP) Documentation/IG-What-is-blockchain-technology-Blocks-with-des.png
  Decentralized Application (DAPP) Documentation/README.md
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 005337.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 005710.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 005834.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 005949.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 010114.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 010225.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 010333.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 010624.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 103237.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 103420.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 103616.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 103813.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 103944.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 104139.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 104313.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 110748.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 111737.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 115547.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 123931.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-03 124107.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-04 203924.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-04 204206.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-04 204415.png
  Decentralized Application (DAPP) Documentation/Screenshot 2024-10-04 204539.png
  Decentralized Application (DAPP) Documentation/Understanding_Consensus_Mechanisms_in_Blockchain.jpg
  Decentralized Application (DAPP) Documentation/bb5cbccab13a4a4e651a942f9abfee83b26e8ac9.webp
  Decentralized Application (DAPP) Documentation/blockchain-cryptography.webp
  Decentralized Application (DAPP) Documentation/blockchain-wallet-working.jpg
  Decentralized Application (DAPP) Documentation/centralised-vs-decentralised-business-diagram-600nw-1866499276.webp
  Decentralized Application (DAPP) Documentation/chainlink-network-diagram-1536x1093.webp
  Decentralized Application (DAPP) Documentation/depositphotos_339750616-stock-photo-gold-bitcoin-crypto-currency-on.webp
  Decentralized Application (DAPP) Documentation/pic1.png
  Decentralized Application (DAPP) Documentation/pic2.jpg
  React JS Documentation/README.md
Labels: open-odyssey, dino-accepted

#12 Enhancing ML Model Learning: Comprehensive Documentation for Beginners
  ML documentation/ALLINONE.md
Labels: open-odyssey, dino-accepted

#13 Add Flask Documentation
  Flask Documentation/NEWFILE.md
Labels: open-odyssey, dino-accepted

#14 Unreal Engine Windows Documentation (Done Automatically by Github CLI)
  Unreal Engine Documentation on Windows/README.md
Labels: open-odyssey, dino-accepted

#15 AI in Python on Windows Documentation (PR Automatically Generated by Github CLI)
  AI in Python on Windows/README.md
Labels: open-odyssey, dino-accepted

#16 Add Comprehensive Documentation for Computer System Architecture and Design Principles
  Architecture Systems/README.md
  Solidity Documentation/Readme.md
Labels: open-odyssey, dino-accepted

#17 Python over C
  W Python/slide 1.jpeg
  W Python/slide 2.jpeg
  W Python/slide 3.jpeg
  W Python/slide 4.jpeg
  W Python/slide 5.jpeg
  W Python/slide 6.jpeg
  W Python/slide 7.jpeg
  W Python/slide 8.jpeg
Labels: open-odyssey, dino-accepted

#18 Added documentation for Blender in Windows
  Blender Documentation in Windows/README.md
Labels: open-odyssey, dino-accepted

#19 Added documentation for Docker in Windows
  Docker in Windows/README.md
Labels: open-odyssey, dino-accepted

#20 Added documentation for Web Scraping
  Web Scraping Documentation/README.md
Labels: open-odyssey, dino-accepted

#21 php documentation add
  php documentation/readme.md
Labels: good first issue, open-odyssey, dino-accepted

#22 Added plans for Automated Assignment Reminder
  Automated Assignment Reminder/Automated Assignment Reminder.jpg
  Automated Assignment Reminder/README.md
Labels: open-odyssey, dino-accepted

#25 documentation for Turborepo and monorepo
  TurboRepo & MonoRepo/Readme.md
Labels: open-odyssey, dino-accepted

#26 "Enhanced README with additional details on open-source community and success stories"
  Open Source Documentation/Readme.md
Labels: dino-accepted

#27 Added plans for Library Management System
  Library Management System/Library Management System.jpg
  Library Management System/README.md
Labels: open-odyssey, dino-accepted

#28 Added plans for Online Food Ordering System
  Online Food Ordering System/Online Food Ordering System.jpg
  Online Food Ordering System/README.md
Labels: open-odyssey, dino-accepted

#29 Added plans for Student Information System
  Student Information System/README.md
  Student Information System/Student Information System.jpg
Labels: open-odyssey, dino-accepted

#30 Added plans for ATM Transaction System
  ATM Transaction System/ATM Transaction System.jpg
  ATM Transaction System/README.md
Labels: open-odyssey, dino-accepted

#31 Added plans for Movie Ticket Booking System
  Movie Ticket Booking System/Movie Ticket Booking System.jpg
  Movie Ticket Booking System/README.md
Labels: open-odyssey, dino-accepted

#32 Added plans for E-commerce Website
  E-commerce Website/E-commerce Website.jpg
  E-commerce Website/README.md
Labels: open-odyssey, dino-accepted

#33 Create RESTfulAPI.md
  RESTful API Documentation/RESTfulAPI.md
Labels: dino-accepted

#34 Create graphql.md
  GraphQL Documentation/graphql.md
Labels: open-odyssey, dino-accepted

#35 added documentation for kubernetes
  K8s/Readme.md
Labels: open-odyssey, dino-accepted

#36 Added plans for Hospital Management System
  Hospital Management System/Hospital Management System.jpg
  Hospital Management System/README.md
Labels: open-odyssey, dino-accepted

#37 added docs for authentication
  Authentication docs/README.md
Labels: dino-accepted

#93 Create hashicorp vault documentation
  HashiCorp Vault Documentation/hashicorp.md
Labels: open-odyssey, dino-accepted

#103 Added plans for Content Management System
  Content Management System/Content Management System.jpg
  Content Management System/README.md
Labels: open-odyssey, dino-accepted

#102 Added plans for Bus Reservation System
  Bus Reservation System/Bus Reservation System.jpg
  Bus Reservation System/README.md
Labels: open-odyssey, dino-accepted

#101 Added plans for Loan Management System
  Loan Management System/Loan Management System.jpg
  Loan Management System/README.md
Labels: open-odyssey, dino-accepted

#100 Added plans for Job Portal System
  Job Portal System/Job Portal System.jpg
  Job Portal System/README.md
Labels: open-odyssey, dino-accepted

#99 Added plans for Banking System
  Banking System/Banking System.jpg
  Banking System/README.md
Labels: open-odyssey, dino-accepted

#98 Added plans for Social Networking System
  Social Networking System/README.md
  Social Networking System/Social Networking System.jpg
Labels: open-odyssey, dino-accepted

#95 Added plans for Online Examination System
  Online Examination System/Online Examination System.jpg
  Online Examination System/README.md
Labels: open-odyssey, dino-accepted

#94 new docs for django added in python
  Django docs/readme.md
Labels: open-odyssey, dino-accepted

#92 Create cardano documentation
  Cardano Documentation/cardano.md
Labels: open-odyssey, dino-accepted

#91 Create k3s documentation
  K3s Documentation/k3s.md
Labels: open-odyssey, dino-accepted

#90 Tezos Documentation
  Tezos Documentation/tezos.md
Labels: open-odyssey, dino-accepted

#89 Jenkins Documentation
  Jenkins Documentation/jenkins.md
Labels: open-odyssey, dino-accepted

#88 Create openshift documentation
  Openshift Documentation/openshift.md
Labels: open-odyssey, dino-accepted

#87 Binance Smart Chain Documentation
  Binance Smart Chain Documentation/bsc.md
Labels: open-odyssey, dino-accepted

#85 ClickHouse Documentation
  ClickHouse Documentation/clickhouse.md
Labels: open-odyssey, dino-accepted

#84 Create Vue.js documentation
  Vue.js Documentation/vue.md
Labels: open-odyssey, dino-accepted

#83 Create solana.md
  Solana Documentation/solana.md
Labels: open-odyssey, dino-accepted

#82 Create svelte documentation
  Svelte Documentation/svelte.md
Labels: open-odyssey, dino-accepted

#81 Prometheus Documentation
  Prometheus Documentation/prometheus.md
Labels: open-odyssey, dino-accepted

#80 Create Terraform Documentation
  Terraform Documentation/tf.md
Labels: open-odyssey, dino-accepted

#79 Nginx Documentation
  Nginx Documentation/nginx.md
Labels: open-odyssey, dino-accepted

#78 Create openvpn documentation
  OpenVPN Documentation/openvpn.md
Labels: open-odyssey, dino-accepted

#77 Hyperledger Fabric Documentation
  Hyperledger Fabric Documentation/hypfab.md
Labels: open-odyssey, dino-accepted

#76 Create polkadot documentation
  Polkadot Documentation/polkadot.md
Labels: open-odyssey, dino-accepted

#75 Create Gamemaker studio documentation
  GameMaker Studio Documentation/game.md
Labels: open-odyssey, dino-accepted

#74 Hugging Face Transformers Documentation
  Hugging Face Transformer Documentation/transformer.md
Labels: open-odyssey, dino-accepted

#73 Pandas Documentation
  Pandas Documentation/pandas.md
Labels: open-odyssey, dino-accepted

#72 Create Pytorch Documentation
  Pytorch Documentation/pytorch.md
Labels: open-odyssey, dino-accepted

#71 Create Keras Documentation
  Keras Documentation/keras.md
Labels: open-odyssey, dino-accepted

#70 OpenCV Documentation
  OpenCV Documentation/opencv.md
Labels: open-odyssey, dino-accepted

#69 Create numpy documentation
  Numpy Documentation/numpy.md
Labels: open-odyssey, dino-accepted

#68 Matplotlib Documentation
  Matplotlib Documentation/matplotlib.md
Labels: open-odyssey, dino-accepted

#66 Tensorflow Documentation
  Tensorflow Documentation/tensorflow.md
Labels: open-odyssey, dino-accepted

#65 Create Xgboost documentation
  XGBoost Documentation/xgboost.md
Labels: open-odyssey, dino-accepted

#64 Apache Spark Documentation
  Apache Spark Documentation/apache_spark.md
Labels: open-odyssey, dino-accepted

#63 Create React Native Documentation
  React Native Documentation/react.md
Labels: open-odyssey, dino-accepted

#62 Flutter documentation
  Flutter Documentation/flutter.md
Labels: open-odyssey, dino-accepted

#61 Cypress Documentation
  Cypress Testing Framework Documentation/cypress.md
Labels: open-odyssey, dino-accepted

#60 Create Jest Documentation
  Jest Documentation/jest.md
Labels: open-odyssey, dino-accepted

#59 Grafana Documentation
  Grafana Documentation/grafana.md
Labels: open-odyssey, dino-accepted

#58 Create CircleCl Documentation
  CircleCI Documentation/circle.md
Labels: open-odyssey, dino-accepted

#57 Create redis documentation
  Redis Documentation/redis.md
Labels: open-odyssey, dino-accepted

#56 Apache Cassandra Documentation
  Cassandra Documentation/cassandra.md
Labels: open-odyssey, dino-accepted

#55 Create Inter Planetary File System
  IPFS (Inter Planetary FIle System) Documentation/ipfs.md
Labels: open-odyssey, dino-accepted

#54 BitTorrent Documentation
  BitTorrent Documentation/torrent.md
Labels: open-odyssey, dino-accepted

#53 Added plans for Food Delivery System
  Food Delivery System/Food Delivery System.jpg
  Food Delivery System/README.md
Labels: open-odyssey, dino-accepted

#52 Created a documentation on DBMS
  DBMS Documentation/Readme.md
Labels: open-odyssey, dino-accepted

#51 Added plans for Flight Reservation System
  Flight Reservation System/Flight Reservation System.jpg
  Flight Reservation System/README.md
Labels: open-odyssey, dino-accepted

#50 Added plans for School Management System
  School Management System/README.md
  School Management System/School Management System.jpg
Labels: open-odyssey, dino-accepted

#49 Added plans for Hotel Booking System
  Hotel Booking System/Hotel Booking System.jpg
  Hotel Booking System/README.md
Labels: open-odyssey, dino-accepted

#47 Created a documentation on Generative AI
  Generative AI documentation/ai.md
Labels: open-odyssey, dino-accepted

#46 Processor Architecture Documentation
  Processor Architecture Documantation/processor.md
Labels: open-odyssey, dino-accepted

#45 Created a documentation on Gyroscopic Sensor
  Gyroscopic Sensor Documentation/gyroscopic.md
Labels: open-odyssey, dino-accepted

#43 Created documentation on Firebase
  Firebase documentation/firebase.md
Labels: open-odyssey, dino-accepted

#42 Kotlin documentation
  Kotlin Documentation/kotlin.md
Labels: open-odyssey, dino-accepted

#41 Create documentation on ESP32 Module
  ESP32 Module Documentation/esp32.md
Labels: open-odyssey, dino-accepted

#40 Arduino Nano Documentation
  Arduino Nano Documentation/arduino_nano.md
Labels: open-odyssey, dino-accepted

#39 Created documentation on google cloud services
  Google Cloud Services Documentation/gcs.md
Labels: open-odyssey, dino-accepted

#38 Amazon Web Services (AWS) documentation
  Amazon Web Services Documentation/aws.md
Labels: open-odyssey, dino-accepted

#44 IR Sensor Documentation
  IR Sensor Documentation/ir_sensor.md
Labels: open-odyssey, dino-accepted

#48 Added plans for Inventory Management System
  Inventory Management System/Inventory Management System.jpg
  Inventory Management System/README.md
Labels: open-odyssey, dino-accepted

#96 added Strappi Documentation
  Strapi Documentation/README.md
Labels: open-odyssey, dino-accepted

#97 added AppFlowy Documentation
  AppFlowy Documentation/README.md
Labels: open-odyssey, dino-accepted

#104 Add files via upload
  Docker Documentation/readme.md
Labels: open-odyssey, dino-accepted

#105 added NocoDB Documentation
  NocoDB Documentation/README.md
Labels: open-odyssey, dino-accepted

#106 added n8n Documentation
  n8n Documentation/README.md
Labels: open-odyssey, dino-accepted

#107 added FlowiseAI Documentation
  Flowise Documentation/README.md
Labels: open-odyssey, dino-accepted

#108 Create Readme.md of documentation on SQL
  SQL Documentation/Readme.md
Labels: open-odyssey, dino-accepted

#109 Created Readme.md of documentation on version control and git basics
  Version Control and Git Basics/Readme.md
Labels: open-odyssey, dino-accepted

#110 Azure and SpringBoot Documentation Added
  Azure Documentation/azure.md
  SpringBoot Documentation/spring.md
Labels: open-odyssey, dino-accepted
